Update documentation and create script for s3-example
vertica/spark-connector pull request #105
Opened 2021-06-02 23:51 UTC by ravjotbrar

### Summary

Updated documentation for s3-example so users do not try and compile inside docker container. Also, created a script for S3 setup.

### Description

Removed documentation that asked user to create a lib directory for the JAR inside s3-example. Also, asked users to run 'sbt assembly' before entering the sandbox environment in docker. This speeds up the compile time and avoids memory issues. In addition, created a script which involves all of the setup required for s3. This simplifies running the s3 example. 

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-77204

### Additional Reviewers

@jonathanl-bq 
@alexr-bq

2021-06-02 23:59 UTC, jonathanl-bq requested changes

2021-06-02 23:59 UTC, jonathanl-bq commented on examples/s3-example/build.sbt
> +name := "spark-vertica-connector-s3-example"
Shouldn't we be adding the jar as a library dependency here? We're removing the lib folder instructions, so I don't know where this example would get its jar from.

2021-06-03 00:09 UTC, ravjotbrar commented on examples/s3-example/build.sbt
> +name := "spark-vertica-connector-s3-example"
Added

2021-06-03 19:21 UTC, alexr-bq approved these changes

2021-06-03 19:58 UTC, jonathanl-bq approved these changes

2021-06-03 20:03 UTC, merged