S3 integration
vertica/spark-connector pull request #109
Opened 2021-06-08 18:37 UTC by ravjotbrar

### Summary

Added support in workflow to run integration tests against S3. 

### Description

Created a new job in the main CI file, which automates the spark cluster setup in docker. Also, source S3 credentials via GitHub secrets and pass them into the configuration file or to environment variables in docker container. 

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-76345

### Additional Reviewers

@alexr-bq 
@jonathanl-bq

2021-06-14 17:04 UTC, alexr-bq requested changes
Move to a different workflow

2021-06-14 18:17 UTC, ravjotbrar commented
> Move to a different workflow

Done.

2021-06-14 18:29 UTC, jonathanl-bq approved these changes

2021-06-15 18:51 UTC, alexr-bq approved these changes

2021-06-15 18:56 UTC, merged