Reorganize documentation
vertica/spark-connector pull request #113
Opened 2021-06-16 01:02 UTC by ravjotbrar

### Summary

This change updates our documentation and creates a script that accepts example JAR files as an argument.

### Description

Updated the functional-tests README to include the new connector version, sandbox-clientenv.sh script, and guide to running against S3. In addition, added required Scala version to connector README, removed run-example.sh scripts from each individual example directory and added a general script that accepts a parameter for the target JAR. As a result, examples README updated to show how to run application using 'sbt run' and 'spark-submit'.

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-77623
http://jira.verticacorp.com:8080/jira/browse/VER-77627

### Additional Reviewers

@alexr-bq 
@jonathanl-bq

2021-06-16 23:17 UTC, alexey-temnikov requested changes

2021-06-16 23:17 UTC, alexey-temnikov commented on README.md
> +For the Scala API, Spark 3.0.0 and above use Scala 2.12. You will need to use a compatible Scala version (2.12.x).
What is the Scala API?  Should we just use rephrase it as - "Spark connector requires Scala version 2.12.x"? Should we mention a specific Scala version?

2021-06-16 23:17 UTC, alexey-temnikov commented on examples/README.md
> +**Note**: The instructions for running the S3, Kerberos, and PySpark example are different. If you would like to run that example, please see their respective READMEs.
Shall we add sentence explaining why instructions are different? I.e. we do have different example running Spark with prebuilt hadoop vs spark with user provided hadoop?

2021-06-16 23:17 UTC, alexey-temnikov commented on examples/README.md
> +After changing your directory to a specific example (such as spark-connector/examples/basic-read), just enter sbt run
It might be better to use `sbt run` instead of sbt run

2021-06-16 23:17 UTC, alexey-temnikov commented on examples/target/.history
> +;set _root_.scala.collection.Seq(historyPath := None,shellPrompt := { _ => "" },SettingKey[_root_.scala.Option[_root_.sbt.File]]("sbtStructureOutputFile") in _root_.sbt.Global := _root_.scala.Some(_r
Exclude from the commit / repo.

2021-06-16 23:17 UTC, alexey-temnikov commented on examples/target/scala-2.12/update/update_cache_2.12/inputs
> +220233665
exclude target from the repo (add to .gitignore) and remove from the PR.

2021-06-16 23:17 UTC, alexey-temnikov commented on examples/target/scala-2.12/update/update_cache_2.12/output
> +{"cachedDescriptor":".","configurations":[{"configuration":{"name":"plugin"},"modules":[],"details":[]},{"configuration":{"name":"pom"},"modules":[],"details":[]},{"configuration":{"name":"test"},"mo
Exclude `target`

2021-06-16 23:49 UTC, ravjotbrar commented on README.md
> +For the Scala API, Spark 3.0.0 and above use Scala 2.12. You will need to use a compatible Scala version (2.12.x).
Changed it to "Spark connector requires Scala version 2.12.x". Don't think the specific Scala version matters.

2021-06-16 23:49 UTC, ravjotbrar commented on examples/target/scala-2.12/update/update_cache_2.12/inputs
> +220233665
Added to .gitignore

2021-06-16 23:59 UTC, ravjotbrar commented on examples/README.md
> +**Note**: The instructions for running the S3, Kerberos, and PySpark example are different. If you would like to run that example, please see their respective READMEs.
They're different because they each require their own specific setup. For example, for Kerberos we need to clone the Kerberized Docker setup and for S3 we have to set specific dependencies. I can list the differences, but then we're getting redundant.

2021-06-17 14:41 UTC, alexr-bq commented on README.md
> +For the Scala API, Spark 3.0.0 and above use Scala 2.12. You will need to use a compatible Scala version (2.12.x).
Can you test a few different versions of 2.12.x to confirm this? Thanks.

2021-06-17 14:42 UTC, alexr-bq commented
Build is failing

2021-06-17 14:45 UTC, alexr-bq commented on examples/README.md
> +Running this script for the first time will install Spark and user-provided Hadoop. This may take some time; however, running the script subsequently will forgo those steps. If you would like to incl
Really good solution with the clean option on the script!

2021-06-17 14:46 UTC, alexr-bq requested changes
Fix build

2021-06-17 17:25 UTC, ravjotbrar commented on README.md
> +For the Scala API, Spark 3.0.0 and above use Scala 2.12. You will need to use a compatible Scala version (2.12.x).
Tried on 2.12.2, 2.12.8, and 2.12.14. All work.

2021-06-17 17:29 UTC, ravjotbrar commented
> Build is failing

Had to do with Artima's servers. It's fixed now.

2021-06-17 19:08 UTC, alexr-bq approved these changes

2021-06-17 19:18 UTC, merged