Fix kerberos under yarn: add delegation token search
vertica/spark-connector pull request #114
Opened 2021-06-17 14:32 UTC by alexr-bq

### Summary

Check for existing delegation token before requesting new one. This is required for YARN support.

### Related Issue

VER-77541

### Additional Reviewers

@jonathanl-bq 
@ravjotbrar

2021-06-17 16:16 UTC, NerdLogic commented on connector/src/main/scala/com/vertica/spark/datasource/fs/FileStoreLayerInterface.scala
> +        if (token.getKind.equals(new Text("HDFS_DELEGATION_TOKEN"))) {
Can this be done with `ugiUser.getCredentials.getToken(new Text("HDFS_DELEGATION_TOKEN")`?

2021-06-18 18:49 UTC, jonathanl-bq requested changes

2021-06-18 18:49 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/fs/FileStoreLayerInterface.scala
> +    val ugiUser = UserGroupInformation.getLoginUser
Option(UserGroupInformation.getLoginUser)

2021-06-18 20:30 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/fs/FileStoreLayerInterface.scala
> +        if (token.getKind.equals(new Text("HDFS_DELEGATION_TOKEN"))) {
Tried this, it failed.

2021-06-18 20:33 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/fs/FileStoreLayerInterface.scala
> +    val ugiUser = UserGroupInformation.getLoginUser
done

2021-06-18 20:54 UTC, jonathanl-bq approved these changes

2021-06-18 21:19 UTC, merged