Fix scripts for Pyspark and s3 examples
vertica/spark-connector pull request #116
Opened 2021-06-19 00:35 UTC by jonathanl-bq

### Summary

This change updates documentation and scripts for the PySpark example.

### Description

This change adds automation for the PySpark example to make it easier to run. Previously, we didn't install Python3 or setup the Spark cluster, so this makes it easier to get started. It also adds comments to the Python script to make it easier for people unfamiliar with PySpark to understand what the script is doing. In addition, the READMEs for PySpark and for the examples in general have both been updated.

No changes were required for S3, aside from the README. Apparently, the "bad array subscript" issue I get is only happening for me, and only sometimes. I'll likely need to dig into it a bit more, but for now, this should work fine.

### Related Issue

VER-77686

### Additional Reviewers

@alexr-bq 
@ravjotbrar

2021-06-21 21:33 UTC, ravjotbrar commented on examples/README.md
> +Note: this method is required for the S3-example and PySpark example.
Although running the PySpark example is ran in the spark cluster, the first step listed in this method is an `sbt assembly`, which is not applicable. We might want to clarify that in the README.

2021-06-21 21:35 UTC, ravjotbrar commented on examples/README.md
> +Note: this method is required for the S3-example and PySpark example.
We also use an entirely different script for this example, right?

2021-06-21 21:38 UTC, ravjotbrar requested changes

2021-06-21 21:38 UTC, ravjotbrar commented on examples/pyspark/README.md
> +An example application is provided alongside a .sh file which shows how to run such an application with the connector. It can be run using "./run-example.sh". This script will download Python3, Spark
./run-example.sh should be changed to ./run-python-example.sh, unless we want to supply sparkapp.py as an argument and install python3 in our run-example script.

2021-06-21 21:47 UTC, ravjotbrar commented on examples/s3-example/README.md
We should probably add a step here to cd back into the examples directory.

2021-06-22 20:02 UTC, ravjotbrar commented on examples/s3-example/README.md
Also should we be using sandbox-clientenv.sh instead of manually inputting the docker commands?

2021-06-23 00:40 UTC, jonathanl-bq commented on examples/README.md
> +Note: this method is required for the S3-example and PySpark example.
Somehow, I thought this used SBT, but yes, this shouldn't be here.

2021-06-23 00:40 UTC, jonathanl-bq commented on examples/pyspark/README.md
> +An example application is provided alongside a .sh file which shows how to run such an application with the connector. It can be run using "./run-example.sh". This script will download Python3, Spark
Good catch. Fixed.

2021-06-23 00:41 UTC, jonathanl-bq commented on examples/s3-example/README.md
Yes, this was written before the sandbox-clientenv.sh script was merged. I've updated this now.

2021-06-23 00:54 UTC, ravjotbrar approved these changes

2021-06-23 00:56 UTC, merged