Merge statement prototype
vertica/spark-connector pull request #123
Opened 2021-06-28 22:52 UTC by ravjotbrar

### Summary

With the implementation of merge statements in our connector, users can process raw data in Spark and merge that data with an existing table in Vertica. The processed data will be written to a temporary table in Vertica before being merged. In the existing table, matched records will be updated and new records will be inserted, effectively constituting an “Upsert”. In order to execute a merge statement in our Spark Connector, the user needs to pass in a mergeKey, which will likely be an array of column attributes to join the existing table and temporary table on. If this option is not populated, a write will be performed as usual without the use of a temporary table.

### Description

For this prototype, changes were made to add a new connector option, which is used to pass in the merge key. When in the write pipe, the connector checks for the existence of this merge key, and if it exists, creates a temporary table which will be used for the intermediary copy. The write pipe then uses the JDBC layer to perform the merge from the temporary table into the target table. Two new supporting functions were implemented in SchemaTools to create the merge statement.

### Related Issue

https://github.com/vertica/spark-connector/issues/118

### Additional Reviewers

@alexr-bq 
@jonathanl-bq 
@alexey-temnikov

2021-06-29 19:27 UTC, alexr-bq requested changes
Looks good, prototype so don't merge, create full ticket.

Need:
- list of keys
- true temporary table created as part of session
- unit tests
- integration tests
- consider interaction with overwrite mode
- consider interaction with copy_column_list

2021-06-29 19:57 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/config/WriteConfig.scala
> + * @param mergeKey Key that two data sets are joined on in order to execute a merge statement
How about mergeConditions?

2021-06-29 19:58 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> -      copyStatement = buildCopyStatement(config.tablename.getFullTableName,
Good idea

2021-06-29 21:28 UTC, jonathanl-bq requested changes

2021-06-29 21:28 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      case None => None
How does this work? I'm assuming key is a String, so I'm surprised you can return a None here, since that's not of type String.

2021-06-29 21:28 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +    }
I think you could use isDefined instead

2021-06-29 21:28 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      rowsCopied <- if (config.mergeKey.isDefined) Right(performCopy(copyStatement, tempTableName).left.map(_.context("commit: Failed to copy rows"))) else Right(performCopy(copyStatement, config.tab
Split across multiple lines. Also, you should add different context for each case so we have a bit more debugging information.

2021-06-29 21:28 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    updateColValues
This is overly complicated. Just use mkString instead with a "," separator. See https://www.baeldung.com/scala/join-string-collection

I expect that this should be done without needing a foreach or mutable variables.

2021-06-29 21:28 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    })
Same as below. Use mkString instead.

2021-06-29 21:28 UTC, jonathanl-bq commented on examples/basic-write/build.sbt
> -name := "spark-vertica-connector-basic-write-example"
Why this change? If we're changing this, we should make the other examples consistent with this too.

2021-06-29 21:28 UTC, jonathanl-bq commented on examples/run-example.sh
> +    wget -P ../../ https://mirror.dsrg.utoronto.ca/apache/spark/spark-3.1.2/spark-3.1.2-bin-without-hadoop.tgz
Separate PR for these version changes

2021-06-29 21:33 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      case None => None
I'll change it to "" for now, but will probably need to change it entirely once I update the string to a list.

2021-06-29 21:33 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +    }
I may get rid of this part of the code entirely, since it's not necessary.

2021-06-29 21:35 UTC, ravjotbrar commented on examples/basic-write/build.sbt
> -name := "spark-vertica-connector-basic-write-example"
Changed to basic-write because when we pass in the jar as an argument to run-example.sh, we instruct the user to use the directory name: `./run-example.sh [REPLACE WITH EXAMPLE DIR]/target/scala-2.12/spark-vertica-connector-[REPLACE WITH EXAMPLE DIR]-assembly-2.0.jar`. All other build.sbt files are consistent with this.

2021-06-29 22:19 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      rowsCopied <- if (config.mergeKey.isDefined) Right(performCopy(copyStatement, tempTableName).left.map(_.context("commit: Failed to copy rows"))) else Right(performCopy(copyStatement, config.tab
Good point.

2021-06-29 22:20 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    updateColValues
Will this work even though columnDefs isn't a collection of strings?

2021-06-30 00:15 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    updateColValues
Call .map first

2021-07-13 19:42 UTC, closed without merging