Merge statements
vertica/spark-connector pull request #133
Opened 2021-07-07 03:04 UTC by ravjotbrar

### Summary

This PR finalizes the merge prototype. See linked issue below for more details. 

### Description

The changes include adding the mergeKey option which can be a list of columns, making use of the copy column list option if the column names of the target table and df are different, creating a true temporary table in Vertica, and ignoring the overwrite mode during a merge. Additionally, PR adds appropriate unit tests and integration tests. 

### Related Issue

https://github.com/vertica/spark-connector/issues/129

### Additional Reviewers

@alexr-bq 
@jonathanl-bq 
@alexey-temnikov

2021-07-09 20:47 UTC, jonathanl-bq requested changes

2021-07-09 20:47 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +          Right(buildCopyStatement(fullTableName.toString(), "", url, rejectsTableName, "parquet"))
The empty string parameter is unclear to me. I think it might be better off as a default argument or maybe this should use named parameters.

2021-07-09 20:47 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +          Right(buildCopyStatement(fullTableName.toString(), "", url, rejectsTableName, "parquet"))
Actually, why do we build a copy statement with no columns listed? What does that do?

2021-07-09 20:47 UTC, jonathanl-bq commented on examples/merge-example/src/main/scala/example/TestUtils.scala
> +// (c) Copyright [2020-2021] Micro Focus or one of its affiliates.
I'm not a huge fan of how much we've been copying these TestUtils. They usually provide way more functionality than we really need. We might want to consider removing these modules and just inlining the utility functions used.

2021-07-09 20:47 UTC, jonathanl-bq commented on functional-tests/src/main/scala/com/vertica/spark/functests/EndToEndTests.scala
> +
I'd like to see test cases for:
- merge with no existing table in Vertica
- some updates and some inserts
- all inserts
- all updates
- no updates or inserts

2021-07-09 20:51 UTC, alexr-bq requested changes

2021-07-09 20:51 UTC, alexr-bq commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
change mergeKey to merge key or merge_key

2021-07-09 20:51 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +          Right(buildCopyStatement(fullTableName.toString(), "", url, rejectsTableName, "parquet"))
Could move the if statement to inside the function call for less repetition.

2021-07-09 20:51 UTC, alexr-bq commented on functional-tests/src/main/scala/com/vertica/spark/functests/EndToEndTests.scala
> +  it should "Merge with existing table in Vertica" in {
Add test case for multiple columns in merge key

2021-07-09 20:55 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +    val tableNameMaxLength = 30
I was playing around with the max table name length with the addition of a temp table and have initially moved the location of it. Then I realized that it doesn't impact merge statements so I put it back in an arbitrary but appropriate spot.

2021-07-09 20:59 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +                          Right((""))
Good catch

2021-07-09 20:59 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      }
Good point

2021-07-09 21:00 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +  def getInsertValues(jdbcLayer: JdbcLayerInterface, tableName: TableName, copyColumnList: Option[ValidColumnList]): String
Agreed

2021-07-09 22:39 UTC, ravjotbrar commented on examples/merge-example/src/main/scala/example/TestUtils.scala
> +// (c) Copyright [2020-2021] Micro Focus or one of its affiliates.
That's true

2021-07-09 23:09 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +          Right(buildCopyStatement(fullTableName.toString(), "", url, rejectsTableName, "parquet"))
That parameter is only required for a normal write with customCopyList (I think). Otherwise it's not necessary. I'll change it to a default argument.

2021-07-09 23:16 UTC, ravjotbrar commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
Good catch

2021-07-09 23:40 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +                       else {
Done

2021-07-09 23:40 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        }
Done.

2021-07-09 23:42 UTC, ravjotbrar commented on docker/Dockerfile
> +    curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo && \
Yeah you're right, I'll revert it and merge from main.

2021-07-09 23:42 UTC, ravjotbrar commented on examples/run-example.sh
> +    wget -P ../../ https://mirror.dsrg.utoronto.ca/apache/spark/spark-3.1.2/spark-3.1.2-bin-without-hadoop.tgz
Sounds good.

2021-07-10 00:35 UTC, ravjotbrar commented on functional-tests/src/main/scala/com/vertica/spark/functests/EndToEndTests.scala
> +  it should "Merge with existing table in Vertica" in {
Done

2021-07-10 00:35 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +          Right(buildCopyStatement(fullTableName.toString(), "", url, rejectsTableName, "parquet"))
Done

2021-07-10 00:35 UTC, ravjotbrar commented on functional-tests/src/main/scala/com/vertica/spark/functests/EndToEndTests.scala
> +
Added all test cases except the last, as that doesn't seem possible.

2021-07-10 00:36 UTC, ravjotbrar commented on examples/basic-write/build.sbt
> -name := "spark-vertica-connector-basic-write-example"
Changed

2021-07-12 19:24 UTC, alexey-temnikov commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
Should we add small paragraph explaining how Merge statements are supported? Diagram from https://github.com/vertica/spark-connector/issues/129 might be very helpful.

2021-07-12 19:26 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +    config.get("merge_key")match {
nit: space before match?

2021-07-12 19:54 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +  private val tempTableName = new TableName(config.tablename.name + "_" + config.sessionId, None)
nit: Do we need "new" modifier here?

2021-07-12 19:58 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      _ <- if(config.isOverwrite && !config.mergeKey.isDefined) tableUtils.dropTable(config.tablename) else Right(())
nit: should we use `config.mergeKey.isEmpty` instead of `!config.mergeKey.isDefined`?

2021-07-12 19:59 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      _ <- if (config.isOverwrite && !config.mergeKey.isDefined && tableExistsPre) Left(DropTableError()) else Right(())
nit: same as above, isEmpty?

2021-07-12 20:02 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      copyStatement = buildCopyStatement(fullTableName.toString(), columnList, url, rejectsTableName, "parquet")
nit: is toString() needed?

2021-07-12 20:04 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +   * @param columnDefs List of column definitions from the Vertica table.
What is columnDefs, it is not used in the method?

2021-07-12 20:04 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +   * @param columnDefs List of column definitions from the Vertica table.
What is columnDefs, it is not used in the method?

2021-07-12 20:07 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +      case Some(list) => {
nit: Redundant braces in case clause.

2021-07-12 20:07 UTC, alexey-temnikov commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +          case Right(info) => {
nit: Redundant braces in case clause.

2021-07-12 20:10 UTC, alexey-temnikov commented on connector/src/test/scala/com/vertica/spark/datasource/core/DSWriterTest.scala
> +    mergeKey = None)
Should we use default value in DistributedFilesystemWriteConfig for mergeKey as None (so APIs remain compatible?)

2021-07-12 20:23 UTC, jonathanl-bq requested changes

2021-07-12 20:23 UTC, jonathanl-bq commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
An example comma separated string would be nice. Is it "foo, bar, baz"? Or is it "foo,bar,baz"? Or both?

2021-07-12 20:37 UTC, ravjotbrar commented on connector/src/test/scala/com/vertica/spark/datasource/core/DSWriterTest.scala
> +    mergeKey = None)
Sure, I don't see an issue with that.

2021-07-12 20:52 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +   * @param columnDefs List of column definitions from the Vertica table.
Good catch

2021-07-12 20:57 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      copyStatement = buildCopyStatement(fullTableName.toString(), columnList, url, rejectsTableName, "parquet")
I think it was before, but I might've made some changes that make it unnecessary. Changed.

2021-07-12 21:02 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      _ <- if(config.isOverwrite && !config.mergeKey.isDefined) tableUtils.dropTable(config.tablename) else Right(())
That sounds like it would be more readable.

2021-07-12 21:09 UTC, ravjotbrar commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
Where do you think the best place to add it is? I think it'll make the description of the option too wordy if we put it here.

2021-07-12 21:20 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +  private val tempTableName = new TableName(config.tablename.name + "_" + config.sessionId, None)
I guess not, since it's a case class. Removed.

2021-07-12 22:45 UTC, alexey-temnikov commented on README.md
> +| merge_key                                      | String                                              | In order to execute a merge statement in our Spark Connector, the user needs to pass in a merg
Yes, agree. Considering we have a dedicated example app for merge statements, I'm ok just with this description.

2021-07-13 00:14 UTC, jonathanl-bq requested changes

2021-07-13 00:14 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/config/WriteConfig.scala
> +                                                  mergeKey: Option[ValidColumnList]= None
nit: space before equals

2021-07-13 00:14 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/table/TableUtils.scala
> +
Can this not just be a private method? As far as I can tell, it's just a helper. There's no need to expose this to the implementations.

2021-07-13 00:14 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/table/TableUtils.scala
> +    val statement= buildCreateTableStmt(tablename, schema, strlen, true)
nit: space before equals sign

2021-07-13 00:15 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/table/TableUtils.scala
> +
You mean the buildCreateTableStmt method, right?

2021-07-13 00:33 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/table/TableUtils.scala
> +
yeah, that's what I meant.

2021-07-13 00:33 UTC, jonathanl-bq approved these changes

2021-07-13 00:35 UTC, alexey-temnikov approved these changes

2021-07-13 00:36 UTC, alexey-temnikov approved these changes

2021-07-13 00:38 UTC, merged