Add double quotes around col names to handle reserved keywords
vertica/spark-connector pull request #151
Opened 2021-07-19 23:53 UTC by ravjotbrar

### Summary

This change addresses how reserved keywords used as column names are handled by our connector.

### Description

Added double quotes around column names in reads and merges to be able to handle Vertica's reserved keywords. Also added integration tests to test this.  

### Related Issue

https://github.com/vertica/spark-connector/issues/149

### Additional Reviewers

@alexey-temnikov 
@alexr-bq 
@jonathanl-bq

2021-07-20 20:05 UTC, alexr-bq requested changes

2021-07-20 20:05 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +            "\"" + info.label + "\""
I think we should support the user specifying the column names with quotes around them, and check for that.

2021-07-21 23:15 UTC, jonathanl-bq approved these changes

2021-07-21 23:15 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        val trimmedCols= key.toString.split(",").toList.map(col => col.trim())
nit: space before the = sign

2021-07-21 23:15 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +  private def castToVarchar: String => String = colName => colName + "::varchar AS " + "\"" + colName + "\""
Might be worth making a helper function to just add escaped quotes around strings.

2021-07-22 18:40 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +            "\"" + info.label + "\""
done

2021-07-22 18:40 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +  private def castToVarchar: String => String = colName => colName + "::varchar AS " + "\"" + colName + "\""
done

2021-07-26 21:26 UTC, alexr-bq approved these changes

2021-07-27 22:40 UTC, merged