Update connector version to 2.0.2
vertica/spark-connector pull request #226
Opened 2021-08-30 22:25 UTC by ravjotbrar

### Summary

Update connector version to 2.0.2 to reflect our new release

### Description

Replaced 2.0.1 with 2.0.2 in our project

### Related Issue

https://github.com/vertica/spark-connector/issues/225

### Additional Reviewers

@alexr-bq 
@jonathanl-bq

2021-09-01 20:04 UTC, jonathanl-bq approved these changes

2021-09-02 15:23 UTC, alexey-temnikov requested changes

2021-09-02 15:23 UTC, alexey-temnikov commented on examples/demo/build.sbt
> +  "com.vertica.spark" % "vertica-spark" % "2.0.2-0"
Seems like we should use `2.0.2-slim` instead, as `2.0.2-0` is not published.

2021-09-02 16:50 UTC, ravjotbrar commented on examples/demo/build.sbt
> +  "com.vertica.spark" % "vertica-spark" % "2.0.2-0"
I thought if we don't specify either, then -all is the default?

2021-09-04 17:54 UTC, alexey-temnikov approved these changes

2021-09-07 18:48 UTC, merged