External tables for Existing Data
vertica/spark-connector pull request #233
Opened 2021-09-13 23:16 UTC by ravjotbrar

### Summary

This change implements the second use-case for external tables. Users will now be able to create an external table out of existing parquet data on disk. This is done by using the spark connector to write an _empty_ DF and supplying the path to the existing data in the staging_fs_url config option. In addition, the user must specify the create_external_table config option as "existing" if they want to use existing data or "true" if they want to create an external table out of spark data. 

### Description

Changed the create_external_table option from Bool to Option[String]; the option now accepts "existing", "true", or None. If the user passes in the "existing", the write operation to HDFS is bypassed and a method to infer the schema of the existing data is called. If a user passes in a non-empty dataframe while trying to create an external table using existing data, the connector will error out.

### Related Issue
https://github.com/vertica/spark-connector/issues/200

### Additional Reviewers

@jonathanl-bq 
@alexr-bq

2021-09-15 20:17 UTC, alexr-bq commented on README.md
> +| create_external_table                          | String                                              | An option to create an external table, either out of existing parquet data in HDFS or by writi
I think we should maintain support for "true" here as an option for anyone using the current version.

2021-09-16 00:00 UTC, ravjotbrar commented on README.md
> +| create_external_table                          | String                                              | An option to create an external table, either out of existing parquet data in HDFS or by writi
Done.

2021-09-18 06:55 UTC, jonathanl-bq requested changes
Please also remove and add to .gitignore the hdfs.keytab, vertica.keytab, and hdfs.cert files.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +          case "new-data" => Some(NewData).validNec
nit: I believe you can use an OR pattern here to catch the "true" case in here as well to do this in 1 line.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        if(value.toString == "existing-data") {
Why do we check the string representation? The value is an ADT, so we could just pattern match here instead.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      case Some(value) => if(value.toString == "existing-data") Right(()) else fileStoreLayer.closeWriteParquetFile()
same here, should not use toString.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +                if(createExternalTableOption == "existing-data") Some(createExternalTableStmt.toString) else config.targetTableSql,
same here, avoid checking the string representation.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      createExternalTableOption = config.createExternalTable match {
The typing here is odd. One case returns None, which is an Option, but the other case returns a String. The only common supertype for these two types would be Any, which we really should avoid unless absolutely necessary.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      createExternalTableStmt <- if(createExternalTableOption == "existing-data") inferExternalTableSchema else Right(())
Avoid checking the string here.

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        if(value.toString == "new-data") {
Remove String check

2021-09-18 06:55 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/v2/VerticaDatasourceV2Write.scala
> +          if (value.toString != "existing-data") {
Remove String check.

2021-09-18 06:55 UTC, jonathanl-bq commented on examples/basic-write-example/src/main/resources/application.conf
> -
Please leave this extra line at the end of the file.

2021-09-23 04:10 UTC, jonathanl-bq requested changes

2021-09-23 04:10 UTC, jonathanl-bq commented on examples/external-table-example/build.sbt
> +  //"com.vertica.spark" % "vertica-spark" % "2.0.2-slim"
I'd rather just remove this and maybe leave a note to update this later. Don't forget to update the README for this example as well with instructions on building the connector JAR and placing it in the lib/ folder. We should always make sure our documentation reflects the current state of the project, even if we are going to update it again next release.

2021-09-23 04:10 UTC, jonathanl-bq commented on connector/src/test/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipeTest.scala
> +    (tableUtils.createExternalTable _).expects(tname, Some("create external table \"testtable\"(\"col1\" int) as copy from \'hdfs://example-hdfs:8020/tmp/testtable.parquet/*.parquet\' parquet"), conf
Watch the line length here. I think this is a bit too long and should be split across multiple lines. Ideally, I'd like to avoid having to scroll horizontally just to review this file.

2021-09-23 04:10 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +          col
This makes no sense. The Left value here is going to be swallowed. What are you trying to do here?

2021-09-23 04:10 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +          case field if(addDoubleQuotes(field.name) == colName) => field.dataType.simpleString
This is non-total. There should have been a compiler warning about this, but you aren't handling the other case where the if condition fails.

2021-09-23 17:16 UTC, alexr-bq commented on README.md
> +| create_external_table                          | String                                              | An option to create an external table, either out of existing parquet data in HDFS or by writi
To clarify, I think we should also accept 'true' going forward in code so not break compatibility.

2021-09-23 21:14 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +          case field if(addDoubleQuotes(field.name) == colName) => field.dataType.simpleString
Spoke to Ravjot about this. Apparently, it's supposed to be a partial function, since that's what the Spark API wants.

2021-09-24 03:24 UTC, jonathanl-bq approved these changes

2021-09-28 17:32 UTC, jonathanl-bq approved these changes

2021-09-28 17:32 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +      _ <- if ((config.createExternalTable.isDefined) && config.mergeKey.isDefined) Left(CreateExternalTableMergeKey()) else Right(())
I don't think these parentheses around config.createExternalTable.isDefined are needed.

2021-09-28 17:46 UTC, merged