Handle error when copy is invalid
vertica/spark-connector pull request #291
Opened 2021-12-08 19:32 UTC by ravjotbrar

### Summary

Prior to this change, users would not get a meaningful error when attempting to perform a valid copy. Instead, the connector would give an error where 0 rows were copied and 0 were rejected. This change addresses that issue, along with updating error types in some of the end-end tests. 

### Description

In the commit step, the copy is matched to a Right(int) or Left(err) to indicate the number of rows copied or an error if the copy step could not be performed. As a result, some end to end tests required their error types to be changed from FaultToleranceTestFail to CommitError. In addition, updated some minor nits in the end-end tests. 

### Related Issue

https://github.com/vertica/spark-connector/issues/284
https://github.com/vertica/spark-connector/issues/253

### Additional Reviewers

@jeremyp-bq 
@alexey-temnikov 
@jonathanl-bq 
@alexr-bq

2021-12-08 19:45 UTC, jeremyp-bq approved these changes

2021-12-09 21:40 UTC, jonathanl-bq requested changes

2021-12-09 21:40 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        performCopy(copyStatement, config.tablename)
This change makes no sense. The original code added context to each branch of this if statement to ensure that we could trace which path the code went down in the error. Now we do a performCopy in either case with no distinction. Furthermore, there is no difference between the two cases, making the entire config.mergeKey.isDefined check pointless.

2021-12-09 22:35 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        performCopy(copyStatement, config.tablename)
If you don't think we need the context here, then I'm fine with removing it. However, there is still no distinction between the two cases. Abstractly, you have an if A then B else B, which is the same as B.

2021-12-09 22:37 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        performCopy(copyStatement, config.tablename)
No if you take a look again, the distinction is in the destination of where the copy is performed (temptable for merge and config.tablename otherwise). I don't mind adding the context back in, as I think it can be helpful, but there is still a distinction between the two cases.

2021-12-09 22:50 UTC, ravjotbrar commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +        performCopy(copyStatement, config.tablename)
I see the issue now. The copy paste was a typo, will update.

2021-12-10 00:16 UTC, jonathanl-bq approved these changes

2021-12-10 00:16 UTC, merged