Compatible version checking
vertica/spark-connector pull request #356
Opened 2022-03-29 15:55 UTC by Aryex

### Summary

Previously, complex types errors caused by incompatible Vertica version did not have meaningful error messages. This PR allows the connector to check for Vertica's version number and print out an appropriate error message.

### Description

pre-read and pre-write steps were modified to perform checks vs Vertica's version number. 

### Related Issue

Closes #338 

### Additional Reviewers

@alexey-temnikov 
@alexr-bq 
@jeremyp-bq 
@jonathanl-bq

2022-04-07 17:51 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +import scala.::
Removed.

2022-04-07 18:12 UTC, jeremyp-bq commented on README.md
> +- While maps are only supported in external tables, it can bw modeled as `Array[Row(key, value)]` for use in internal tables. Refer to the Vertica documentation [here](https://www.vertica.com/docs/la
Spelling, "bw" should be "be".

2022-04-07 22:57 UTC, jonathanl-bq requested changes

2022-04-07 22:57 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> +  def getFullContext: String = "Table schema requires at least one native type column"
I know it's kind of annoying, but there's a bunch of codecov warnings in this file because of the new errors being introduced, so you should probably add some tests for them.

2022-04-07 22:57 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> +  override def getFullContext: String = "Internal Vertica tables does not support Map columns. Map data structure can be represented internally as Array[Rows(key, value)]. Refer to Vertica documentat
I find it's more helpful to actually link to the documentation referenced. People always prefer when things are made convenient for them.

2022-04-07 22:57 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/complex/ComplexTypeUtils.scala
> +  private def isNativeType(field: StructField): Either[StructField,StructField] = {
isNativeType is a function name that I would expect to return a boolean value. I think the Either here is a fine choice, but the name of the function is misleading. You could also define your own "Either" using a sealed trait to make the type more readable (Either[StructField, StructField] is a bit long and doesn't tell me much about what is actually returned here).

2022-04-13 15:47 UTC, Aryex commented on README.md
> +- While maps are only supported in external tables, it can bw modeled as `Array[Row(key, value)]` for use in internal tables. Refer to the Vertica documentation [here](https://www.vertica.com/docs/la
fixed

2022-04-13 15:47 UTC, Aryex commented on README.md
> +Complex data types requires at least Vertica 11 and Vertica's JDBC Driver 11.
fixed

2022-04-13 16:08 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/util/complex/ComplexTypeUtils.scala
> +  private def isNativeType(field: StructField): Either[StructField,StructField] = {
Changed to returning boolean instead.

2022-04-13 16:31 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> +  def getFullContext: String = "Table schema requires at least one native type column"
Added.

2022-04-13 21:35 UTC, jonathanl-bq approved these changes

2022-04-13 22:55 UTC, merged