Row write support
vertica/spark-connector pull request #357
Opened 2022-03-29 19:51 UTC by Aryex

### Summary
Added row write support 

### Description

SchemaTools can now parse Spark struct to Vertica Rows
Added support for Arrays[Rows]

### Related Issue

Closes #343

### Additional Reviewers

@alexey-temnikov 
@alexr-bq 
@jeremyp-bq 
@jonathanl-bq

2022-04-07 00:10 UTC, alexr-bq approved these changes

2022-04-07 16:04 UTC, jonathanl-bq requested changes

2022-04-07 16:04 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> +  override def getUserMessage: String = s"${this.error.getClass.getSimpleName}: ${error.getFullContext}"
Did this need to be overridden? I think the default is to just call getFullContext anyway, which this appears to basically be doing.

2022-04-07 16:04 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    makeTableColumnDefs(StructType(fields), strlen, null, arrayLength) match {
Why are we passing in null here?

2022-04-07 17:29 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> +  override def getUserMessage: String = s"${this.error.getClass.getSimpleName}: ${error.getFullContext}"
Good call. I was copying from other errors so I didn't realized it default to getFullContext.

2022-04-07 17:44 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala
> +    makeTableColumnDefs(StructType(fields), strlen, null, arrayLength) match {
Fixed. The argument was for a jdbc layer but it is not being used at all. It was added from PR #336 so must've been an oversight on my end.

2022-04-08 18:32 UTC, jonathanl-bq approved these changes

2022-04-08 20:35 UTC, merged