Adding GCS Support
vertica/spark-connector pull request #385
Opened 2022-05-02 17:59 UTC by Aryex

### Summary

Added support for Google Cloud Storage for use as the staging area for both Spark clusters.

### Description

* Added connector options `gcs_hmac_key_id` and `gcs_hmac_key_secret` to configure access from Vertica to GCS.
* Added connector option `gcs_keyfile` to configure Spark application access to GCS when used outside of GCP clusters.
* Previous AWS methods and objects are refactored to generic names as they are reused by GCS options.
* Added GCS manual and updated Readme

### Related Issue

Closes #376 

### Additional Reviewers
@alexey-temnikov 
@alexr-bq 
@jeremyp-bq 
@jonathanl-bq

2022-05-10 17:04 UTC, jeremyp-bq commented on GCSUserManual.md
> +###Additional Resources
Need a space between the octothorpe and the text.  Same issue in README.md.

2022-05-10 17:28 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +      "VERTICA_GCS_KEY_ID").sequence
I think we should try to be as similar to S3 as possible with the config and env var names.

What about this?:
* `gcs_access_key_id`, `gcs_secret_access_key`
* `fs.gs.access.key.id`, `fs.gs.secret.access.key` (similar to the OAuth values [here](https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#user-credentials))
* `GCS_ACCESS_KEY_ID`, `GCS_SECRET_ACCESS_KEY`

2022-05-10 23:08 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +      "VERTICA_GCS_KEY_ID").sequence
updated

2022-05-10 23:12 UTC, Aryex commented on GCSUserManual.md
> +###Additional Resources
fixed

2022-05-12 20:46 UTC, jeremyp-bq commented on .github/workflows/post-merge-testing.yml
> +      GCS_SERVICE_EMAIL: ${{secrets.GCS_SERVICE_EMAIL}}
Are these needed at this level, or should they only be under the "Run the integration tests against GCS" step below?

2022-05-12 20:54 UTC, jeremyp-bq commented on GCSUserManual.md
> +Finally, ensure that you include the [Google Hadoop Connector](https://mvnrepository.com/artifact/com.google.cloud.bigdataoss/gcs-connector) dependency into your project. Make sure your select the ap
This section does not talk about gcs_service_key_id, gcs_service_key, or gcs_service_email.  I assume they should be mentioned here and when they are needed.

2022-05-12 21:01 UTC, jeremyp-bq commented on GCSUserManual.md
> + * **Running on DataProc clusters:** If your Spark cluster deployed on GCP, you will need to obtain a GCS service account S3 interoperability key to configure connector options `gcs_vertica_key_id` a
Having Vertica in the name, as well as in the Spark/Hadoop option and env var names, is misleading.  These is not Vertica values, they are GCS values.

What about gcs_access_key_id and gcs_secret_access_key?  That way they are still different than the service id and secret, but clear they are only related to GCS.  May also want to change gcs_service_key to gcs_service_secret_key to keep it consistent with AWS params.

2022-05-12 21:02 UTC, jeremyp-bq commented on README.md
> +| gcs_vertica_key_secret                         | String                                              | The GCS S3 interoperability key secret for using GCS as intermediary storage. It is used by Ve
The conditional statements need to be updated, should note that the secret is needed if the id is given and vice-versa.

2022-05-12 21:04 UTC, jeremyp-bq commented on README.md
> +| gcs_service_email                              | String                                              | The GCS service account email. Can be found within the service account json keyfile. Alternati
Add some notes on when each of these is required, and which other params are required if one of these values is set.

2022-05-12 21:12 UTC, jeremyp-bq commented on functional-tests/README.md
> +### Using GCS:
Should we update the S3 instructions above to match GCS?  Seems like some of the commands are already explained in the common section above, and the s3-functional-tests.sh script is not actually S3-specific.

2022-05-13 15:57 UTC, Aryex commented on .github/workflows/post-merge-testing.yml
> +      GCS_SERVICE_EMAIL: ${{secrets.GCS_SERVICE_EMAIL}}
updated

2022-05-13 17:10 UTC, jonathanl-bq commented on .github/workflows/post-merge-testing.yml
> +name: Post-Merge Intergaration Testing.
typo: I think you meant Integration

2022-05-13 17:33 UTC, Aryex commented on README.md
> +| gcs_vertica_key_secret                         | String                                              | The GCS S3 interoperability key secret for using GCS as intermediary storage. It is used by Ve
updated

2022-05-13 17:36 UTC, Aryex commented on README.md
> +| gcs_service_email                              | String                                              | The GCS service account email. Can be found within the service account json keyfile. Alternati
updated

2022-05-13 17:50 UTC, Aryex commented on .github/workflows/post-merge-testing.yml
> +name: Post-Merge Intergaration Testing.
fixed

2022-05-13 18:05 UTC, Aryex commented on GCSUserManual.md
> + * **Running on DataProc clusters:** If your Spark cluster deployed on GCP, you will need to obtain a GCS service account S3 interoperability key to configure connector options `gcs_vertica_key_id` a
updated. Changed back to gcs_hmac since a google search of gcs_hmac key points to what we want.

2022-05-13 21:15 UTC, jonathanl-bq requested changes

2022-05-13 21:15 UTC, jonathanl-bq commented on connector/src/test/scala/com/vertica/spark/datasource/core/DSConfigSetupTest.scala
> +  it should "get GCS Vertica auth from Spark confutation options" in {
typo here in confutation

2022-05-13 22:32 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/config/FileStoreConfig.scala
> +final case class FileStoreConfig(baseAddress: String, sessionId: String, preventCleanup: Boolean, awsOptions: AWSOptions, gcsOptions: GCSOptions) {
I think one is ignored over the other since what matters is the file path. For example, S3 paths starts with `s3a://`, hdsf is 'webhdfs://', gcs is 'gs://'. Hadoop uses this to get the correct file system implementation. Thus, if we do specify both options, they will still be delivered to Hadoop which should pass them down which should then be ignored if not recognized. Furthermore, Aws options shouldn't conflict with gcs since their prefixes are different.

2022-05-13 22:33 UTC, Aryex commented on GCSUserManual.md
> +The instruction on obtaining the key can be found [here](https://cloud.google.com/storage/docs/authentication/managing-hmackeys#create).
updated

2022-05-13 22:36 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +      getFromConnectorOptions(visibility)(
fixed

2022-05-13 22:37 UTC, Aryex commented on connector/src/test/scala/com/vertica/spark/datasource/core/DSConfigSetupTest.scala
> +  it should "get GCS Vertica auth from Spark confutation options" in {
fixed

2022-05-13 22:53 UTC, Aryex commented on .github/workflows/post-merge-testing.yml
> +        run: cd functional-tests/src/main/resources && echo -e 'functional-tests={ \n\thost="'"vertica"'" \n\tport="'"5433"'" \n\tdb="'"docker"'" \n\tuser="'"dbadmin"'" \n\tpassword="'""'" \n\tlog='t
updated

2022-05-16 16:18 UTC, Aryex commented on functional-tests/README.md
> +### Using GCS:
updated

2022-05-16 19:50 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/config/FileStoreConfig.scala
> +final case class FileStoreConfig(baseAddress: String, sessionId: String, preventCleanup: Boolean, awsOptions: AWSOptions, gcsOptions: GCSOptions) {
Right, okay. Just making sure we haven't let anything slip through the cracks.

2022-05-16 19:53 UTC, jonathanl-bq approved these changes

2022-05-16 22:30 UTC, jeremyp-bq approved these changes

2022-05-16 22:57 UTC, merged