Fixing multiple JDBC connections
vertica/spark-connector pull request #400
Opened 2022-05-19 18:39 UTC by Aryex

### Summary

Fixed an issue with the connector creating multiple JDBC connections on write. 

### Description

When checking for jdbc layer is closed, included a lazy initialization check to ensure we don't initialize jdbc connection when it wasn't used. 
This fix is not ideal and in the future, we should look refactor jdbc codes so that they do not have a jdbc layer reference. 

#### Other changes
 * Post merge functional tests added
 * Docker setup to expose Spark UI
 * Fixed weekly tests hadoop version

### Related Issue

Closes #398 

### Additional Reviewers

@alexr-bq 
@jeremyp-bq 
@jonathanl-bq

2022-05-20 19:07 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/jdbc/VerticaJdbcLayer.scala
> +      case None => "0.no-active-session"
What's the significance of this value, why not "0.0" or "na" if we can't get the version?

2022-05-20 19:09 UTC, jeremyp-bq commented on docker/docker-compose.yml
> +      - "8081:8081"
Why do we need to map these ports?

2022-05-20 21:25 UTC, jeremyp-bq commented on functional-tests/default-config.sh
> +echo -e 'functional-tests {
What is this for, was this for testing possible issues with quoted values?

2022-05-20 21:27 UTC, jeremyp-bq commented on functional-tests/src/main/scala/Main.scala
> -        println(s"  ${failedTest.message}")
Are you removing the error message since it is in the output above (i.e. this part is only a summary)?  Might still be useful to print out the root cause message at the end of the test results.

2022-05-20 21:32 UTC, jeremyp-bq commented on functional-tests/src/main/scala/com/vertica/spark/functests/endtoend/RemoteTests.scala
> + * Test suites for submitting to a remote driver.
What is the difference between the "remote" tests and other tests, is it just that this one is meant to be run with the sh script which starts up a Spark master and worker?  Maybe just add that to the comment here so people know what the remote driver/tests means.

2022-05-20 21:39 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/jdbc/VerticaJdbcLayer.scala
> +      case None => "0.no-active-session"
Fixed.

2022-05-20 21:40 UTC, Aryex commented on docker/docker-compose.yml
> +      - "8081:8081"
They are for Spark UI. 8080 is for the driver ui and 8081 is for the executor node.

2022-05-20 21:46 UTC, Aryex commented on functional-tests/default-config.sh
> +echo -e 'functional-tests {
Just a convenient script to reset the config

2022-05-20 21:50 UTC, Aryex commented on functional-tests/src/main/scala/Main.scala
> -        println(s"  ${failedTest.message}")
That was my initial intention. However, I found that the error message would sometime contain the stack trace which clutters the output.

2022-05-20 21:54 UTC, jonathanl-bq requested changes

2022-05-20 21:54 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/factory/VerticaPipeFactory.scala
> +        val jdbcLayer = writeLayerJdbc.orNull
Can we avoid the usage of null here? This is kind of sneaky and it'll make things harder to reason with if it ends up being null here.

2022-05-20 21:56 UTC, Aryex commented on functional-tests/src/main/scala/com/vertica/spark/functests/endtoend/RemoteTests.scala
> + * Test suites for submitting to a remote driver.
Updated. Currently, all of our tests initialize a spark session with `master("local[*]")` which essentially hardcoded them to run on local spark threads, even if we submit them. The RemoteTests overrode it so we can specify the master URL when submitting them.

2022-05-20 21:58 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSWriter.scala
> +class DSWriter(config: WriteConfig, uniqueId: String, pipeFactory: VerticaPipeFactoryInterface = VerticaPipeFactory, jdbc: Boolean = false) extends DSWriterInterface {
Removed.

2022-05-20 22:02 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/factory/VerticaPipeFactory.scala
> +        val jdbcLayer = writeLayerJdbc.orNull
Yeah, its not ideal but checkJdbcLayer() should guarantee that we never have a null jdbc reference in the optional.

2022-05-20 22:32 UTC, jeremyp-bq commented on docker/docker-compose.yml
> +      - "8081:8081"
I think we should add them to the kerberos docker-compose file as well then to keep it consistent.

I could see us creating a multi-node Spark cluster within Docker at some point in the future rather than creating a single master and worker in the client container.  But that is down the road.

2022-05-20 22:49 UTC, Aryex commented on docker/docker-compose.yml
> +      - "8081:8081"
updated

2022-05-20 22:51 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/factory/VerticaPipeFactory.scala
> +        val jdbcLayer = writeLayerJdbc.orNull
updated

2022-05-20 23:43 UTC, Aryex commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSWriter.scala
> +  logger.debug(thread + "Initializing writer")
added a ticket for it

2022-05-23 20:42 UTC, alexr-bq commented
My only additional thought here is - would it be possible to modify the jdbc configuration so that it is never sent down to the executors at all, making it impossible they'll ever try a proper jdbc connection?

2022-05-24 16:04 UTC, Aryex commented
> My only additional thought here is - would it be possible to modify the jdbc configuration so that it is never sent down to the executors at all, making it impossible they'll ever try a proper jdbc connection?

It's possible, but we will need to refactor the pipes which will have a larger scope than this.

2022-05-25 16:53 UTC, jonathanl-bq approved these changes

2022-05-25 19:01 UTC, jeremyp-bq approved these changes

2022-05-25 19:14 UTC, merged