Add parquet export support for complex types as of Vertica 12.0.2
vertica/spark-connector pull request #517
Opened 2022-11-15 20:26 UTC by ai-bq

### Summary

Vertica 12.0.2 is adding full support of Parquet export for complex types. Spark Connector needed to be updated in a way that

1. JSON Export is no longer forced when a complex type column is registered on initial scan
2. Any user who is on a prior version of Vertica still has this JSON Export as the default case

### Description

The VerticaScanBuilder runs prior to the Spark read pipe and includes a JSON check which returns true if complex columns are found in the table schema. This function remains the same with the exception of a conditional that checks the version of Vertica (>12.0.2 does not need this complex type check).

To successfully fetch the version of Vertica, it is added as a param of VerticaReadMetadata and passed along when VerticaScanBuilder fetches Vertica metadata in the JSON check.

### Related Issue

Closes #499. 

### Additional Reviewers

@alexey-temnikov 
@alexr-bq 
@jonathanl-bq 
@jeremyp-bq

2022-11-17 18:45 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/v2/VerticaDatasourceV2Read.scala
> +            else if(metadata.version < VerticaVersionUtils.VERTICA_12_0_2) {
I'm wondering if we should put this logic under a method in VerticaVersionUtils (e.g. VerticaVersionUtils.checkComplexTypesParquetExport(version: Version)).

Unfortunately, I see there is inconsistency between using the VersionUtils class to determine functionality, and only using the version numbers defined in that class with logic in other classes.

2022-11-17 18:48 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +  override def getTableMeta(config: ReadConfig): ConnectorResult[VerticaReadMetadata] =  {
We discussed offline that we could probably refactor getTableSchema and getTableMeta into a single method since they are mostly identical, then have the calling class get what they need from the returned metadata object (schema and/or version).

2022-11-17 18:49 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/v2/VerticaDatasourceV2Read.scala
> +            if(config.useJson) true
This is what is causing the build to fail, need to add braces around if statements to satisfy the scalastyle.

2022-11-21 17:11 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +  def getTableMeta(config: T): ConnectorResult[VerticaReadMetadata]
nit: Rename to getTableMetadata as we refer to it as metadata, not meta, in all other functions/variables.

2022-11-21 17:14 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/util/version/VerticaVersionUtils.scala
> +    val complexTypeFound = complexTypeCols.nonEmpty
complexTypeFound is not used in this function.

Also, this function is for export from Vertica, so should the check below be for ComplexTypeReadNotSupported?

2022-11-21 17:51 UTC, jonathanl-bq requested changes

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +
nit: try to be careful about adding additional whitespace to files, since it creates noise for the reviewers

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +   * @param version Contains the version number for Vertica.
The doc comment is out of sync with the method parameters again

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +  override def getTableMeta(config: WriteConfig): ConnectorResult[VerticaReadMetadata] = Right(VerticaReadMetadata(new StructType(), VerticaVersionUtils.VERTICA_DEFAULT))
If we always return an empty schema, we could change this method to not return a ConnectorResult to indicate that it is infallible. More importantly, we should not be returning **READ** metadata from a **WRITE** method. It's just a naming thing, but I would be more comfortable if it was "VerticaWriteMetadata" or if it can be returned in both Read and Write cases, just "VerticaMetadata".

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +
nit: extra newline

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/v2/VerticaDatasourceV2Read.scala
> +                case Left(_) => ctTools.filterComplexTypeColumns(schema).nonEmpty
Since we're catching an error here, might it make sense to log something to indicate that we're catching an error and falling back on a different approach?

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/version/VerticaVersionUtils.scala
> +    if (version.lessThan(VERTICA_12_0_2)) {
nit: This makes me think we should have just implemented an Ord instance on Version so we could just use the regular < operator here instead of defining our own lessThan method.

2022-11-21 17:51 UTC, jonathanl-bq commented on connector/src/test/scala/com/vertica/spark/common/TestObjects.scala
> +import com.vertica.spark.util.version.Version
Why is this imported if it isn't being used anywhere here?

2022-11-24 19:34 UTC, ai-bq commented on connector/src/main/scala/com/vertica/spark/util/version/VerticaVersionUtils.scala
> +    if (version.lessThan(VERTICA_12_0_2)) {
I think that's a good idea but I'm gonna leave that for another ticket as it could possibly lead to more refactoring on this one

2022-11-24 20:13 UTC, jeremyp-bq commented on connector/src/main/scala/com/vertica/spark/util/version/VerticaVersionUtils.scala
> +    if (version.lessThan(VERTICA_12_0_2)) {
BTW, was just looking and the Version class and it already extends Ordered.  So we can use the various logical operators without any changes, not sure why the string operators were added.

But agree, it should be done as a separate ticket to clean that up.

2022-11-24 20:15 UTC, jeremyp-bq approved these changes

2022-11-25 00:52 UTC, jonathanl-bq approved these changes

2022-11-25 19:26 UTC, merged