added some debugging info related to timed operations
vertica/spark-connector pull request #528
Opened 2022-12-14 18:04 UTC by ai-bq

### Summary

A customer recently asked for more information regarding debugging through the timed_operations parameter. 

### Description

Added a new debugging file to the docs that describes how to go about using the timed_operation parameter and what to look for.  The parameter table on the main README.md links to this file.

### Related Issue

#527 

### Additional Reviewers

@alexey-temnikov 
@alexr-bq

2022-12-15 16:45 UTC, alexey-temnikov commented on docs/debugging.md
> +# Timed Operations
The top Level section should be - The troubleshooting Guide. Instead of timed operations - we need to add a section on how to configure debug logs and what is included in the debug logs (including information about the time).

2022-12-15 16:45 UTC, alexey-temnikov requested changes
The top Level section should be - The troubleshooting Guide. Instead of timed operations - we need to add a section on how to configure debug logs and what is included in the debug logs (including information about the time).

2022-12-15 18:07 UTC, alexr-bq commented on docs/debugging.md
> +The last two are similar but the former is reading the metadata while the latter performs the read.
Don't think this is quite right. The actual read should be 
Timed operation: Partition Read

I think this might go to the worker log rather than the driver log

2023-01-03 18:01 UTC, jeremyp-bq commented on README.md
> +| time_operations                                | Boolean                                             | Whether parts of the connector operation should be timed. Timing information will be [logged](
The link is now out of date.  And you can link to a section by name, e.g.:
```
Timing information will be logged as per the [Troubleshooting Guide](docs/troubleshooting-guide.md#Timed-Operations).
```

We may also want to refer to the Troubleshooting Guide near the bottom of this README (under the Additional Guides section).

2023-01-03 19:17 UTC, ai-bq commented on README.md
> +| time_operations                                | Boolean                                             | Whether parts of the connector operation should be timed. Timing information will be [logged](
Oh good catch thanks. Also I'll add the stuff from our main README as well as I believe that explains how to properly log in cluster mode whereas I've just detailed client mode.

2023-01-05 22:13 UTC, jeremyp-bq commented on docs/troubleshooting-guide.md
> +Our connector logs major events when reading and writing, such as when it is copying a table from the intermediary file store into Vertica or exporting from Vertica into the intermediary file store.
To avoid duplicating this info I think we can remove this from the top-level README.md and reference this guide under the Additional Guides section (e.g. "For information on logging and troubleshooting common issues, see the troubleshooting guide.").

Could also bring the HDFS error under the Limitations section into this document.

2023-01-06 20:13 UTC, jeremyp-bq approved these changes

2023-01-11 19:47 UTC, alexey-temnikov approved these changes

2023-01-17 19:11 UTC, merged