VER-76333: Data generation for performance tests
vertica/spark-connector pull request #65
Opened 2021-04-16 21:59 UTC by alexr-bq

### Summary

Adds performance testing project w/ Data Gen Utils.

### Description

This adds a performance testing project with a utility class for generating data using spark.

Also fixes an issue where permissions were not being used properly when interacting with HDFS.

### Related Issue

VER-76333

### Additional Reviewers

@jonathanl-bq 
@NerdLogic

2021-04-20 23:46 UTC, jonathanl-bq requested changes

2021-04-20 23:46 UTC, jonathanl-bq commented on performance-tests/src/main/scala/com/vertica/spark/perftests/PerformanceTestSuite.scala
> +}
I don't think you need these curly braces

2021-04-20 23:46 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +    val perm = "777"
How much effort is it to get this?

2021-04-20 23:46 UTC, jonathanl-bq commented on connector/src/test/scala/com/vertica/spark/datasource/core/DSWriterTest.scala
> +  val config: DistributedFilesystemWriteConfig = DistributedFilesystemWriteConfig(logLevel = Level.ERROR, jdbcConfig = jdbcConfig, fileStoreConfig = fileStoreConfig,  tablename = tablename, schema =
split over multiple lines

2021-04-20 23:46 UTC, jonathanl-bq commented on functional-tests/.bsp/sbt.json
> -{"name":"sbt","version":"1.4.1","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/bin/java","-Xms100m","-Xmx100m","-classpath","/usr/share
Is this file supposed to be here?

2021-04-20 23:46 UTC, jonathanl-bq commented on connector/src/test/scala/com/vertica/spark/datasource/v2/VerticaV2SourceTest.scala
> +  val writeConfig: DistributedFilesystemWriteConfig = DistributedFilesystemWriteConfig(logLevel = Level.ERROR, jdbcConfig = jdbcConfig, fileStoreConfig = fileStoreConfig,  tablename = tablename, sche
multiple lines

2021-04-20 23:46 UTC, jonathanl-bq commented on functional-tests/src/main/scala/com/vertica/spark/functests/CleanupUtilTests.scala
> +    fsLayer.createDir(path, "777")
Probably better to just make this a constant

2021-04-20 23:46 UTC, jonathanl-bq commented on functional-tests/src/main/scala/com/vertica/spark/functests/HDFSTests.scala
> +      _ <- fsLayer.createDir(path, "777")
Make this a constant

2021-04-20 23:46 UTC, jonathanl-bq commented on performance-tests/src/main/scala/com/vertica/spark/perftests/DataGenUtils.scala
> +    val ms = -946771200000L + (Math.abs(rand.nextLong) % (70L * 365 * 24 * 60 * 60 * 1000))
define the time conversion math as a separate function(s)

2021-04-20 23:46 UTC, jonathanl-bq commented on performance-tests/src/main/scala/com/vertica/spark/perftests/PerformanceTestSuite.scala
> +case class DataRunDef(opts: Map[String, String], df: DataFrame, cols: Int, rows: Int, runs: Int, mode: String) {
I'd avoid stringly typed APIs, like making the mode a String. It could be a sealed trait with case objects.

2021-04-21 18:27 UTC, alexr-bq commented on performance-tests/src/main/scala/com/vertica/spark/perftests/PerformanceTestSuite.scala
> +case class DataRunDef(opts: Map[String, String], df: DataFrame, cols: Int, rows: Int, runs: Int, mode: String) {
Wouldn't have done this in main connector code, was accepting for sake of speed in these small projects. Can fix though.

2021-04-21 18:29 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/VerticaDistributedFilesystemWritePipe.scala
> +    val perm = "777"
done

2021-04-21 18:32 UTC, alexr-bq commented on functional-tests/.bsp/sbt.json
> -{"name":"sbt","version":"1.4.1","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/usr/lib/jvm/java-11-openjdk-11.0.10.0.9-1.el7_9.x86_64/bin/java","-Xms100m","-Xmx100m","-classpath","/usr/share
nope, thus deleted

2021-04-21 20:22 UTC, jonathanl-bq approved these changes
Fix the one comment and then merge.

2021-04-21 20:22 UTC, jonathanl-bq commented on performance-tests/src/main/scala/com/vertica/spark/perftests/DataGenUtils.scala
> +    val ms = -946771200000L + (Math.abs(rand.nextLong) % (70L * 365 * 24 * 60 * 60 * 1000))
This still hasn't been changed. It's very hard to read 70L * 365 * ... etc. and understand what that's doing at a glance.

2021-04-21 21:55 UTC, merged