Ver 77027: Documentation in GitHub / Userguide to setup connector
vertica/spark-connector pull request #68
Opened 2021-04-26 21:22 UTC by jonathanl-bq

### Summary

This change adds a user guide for setting up the docker containers and running the examples in the repo.

### Description

This change adds a new README file to the examples directory, explaining how to setup the docker containers and run the examples.

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-77027

### Additional Reviewers
@alexr-bq 
@NerdLogic

2021-04-29 19:08 UTC, alexr-bq approved these changes

2021-05-03 18:41 UTC, alexr-bq requested changes
Modify the functional-tests readme to be consistent with this too.

2021-05-03 18:44 UTC, alexr-bq commented
I'm getting the following error when trying to run docker compose up -d

ERROR: pull access denied for client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

2021-05-04 00:54 UTC, alexey-temnikov commented on examples/README.md
> +docker-compose up -d
Few Errors what I got - 
`ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.`

`ERROR: pull access denied for client, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

The last error occurs even after login.

2021-05-04 17:32 UTC, jonathanl-bq commented on examples/README.md
> +docker-compose up -d
Right, you need to build the client image first. I've added that in the updated PR.

2021-05-04 17:35 UTC, alexey-temnikov commented on examples/README.md
> +docker-compose up -d
Can we update the docket compose file, so it is build automatically. This might be a much better user experience - 

instead of `image: client` - replace with `build: .` ?

2021-05-04 22:36 UTC, alexr-bq approved these changes

2021-05-04 23:07 UTC, merged