Error message improvements
vertica/spark-connector pull request #74
Opened 2021-05-05 17:31 UTC by alexr-bq

### Summary

Improves error messages and integration tests handling thereof.

### Description

Went through common misconfigurations and our list of errors to make common cases more user friendly. Also fixed integration tests to look for specific error types.

### Related Issue

VER-76910

### Additional Reviewers

@jonathanl-bq 
@NerdLogic

2021-05-06 22:52 UTC, jonathanl-bq requested changes

2021-05-06 22:52 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> -// TODO: Remove
I still want to remove this. It's not correct to consider this an error.

2021-05-06 22:52 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +          case None => Left(SchemaDiscoveryError())
I'm glad we're getting rid of some of these errors wrapping Options. I think it'd be nice to get rid of all of them and replace them with .context() calls. Not something to take action on right now, but something I'd like to see going forward.

2021-05-06 22:52 UTC, jonathanl-bq commented on examples/kerberos-example/src/main/scala/example/Main.scala
> +    //println("KERBEROS DEMO, WROTE TABLE")
Probably should remove this commented out code.

2021-05-06 22:52 UTC, jonathanl-bq commented on functional-tests/build.sbt
> +//unmanagedClasspath in Runtime += new File("/etc/hadoop/conf/")
I'm confused. We removed this before, but now we're bringing it back?

2021-05-06 22:52 UTC, jonathanl-bq commented on functional-tests/src/main/resources/application.conf
> +
nit: revert

2021-05-07 01:35 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> -// TODO: Remove
Noted, but I think we can avoid todo comments like this for the release. Can create a ticket if one doesn't exist.

2021-05-07 01:37 UTC, alexr-bq commented on functional-tests/build.sbt
> +//unmanagedClasspath in Runtime += new File("/etc/hadoop/conf/")
I changed my mind, too useful to have if we need it. Should look into making it conditional but I haven't gotten to it.

2021-05-07 01:38 UTC, alexr-bq commented on examples/kerberos-example/src/main/scala/example/Main.scala
> +    //println("KERBEROS DEMO, WROTE TABLE")
Fixed

2021-05-07 05:37 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/util/error/ErrorHandling.scala
> -// TODO: Remove
I'm not sure what's worse in terms of optics. I guess we can take out the TODO, but I wouldn't be surprised if this "error" raises some eyebrows.

2021-05-07 05:47 UTC, jonathanl-bq approved these changes

2021-05-07 06:25 UTC, merged