Change examples to use jar from maven central and test
vertica/spark-connector pull request #80
Opened 2021-05-14 19:53 UTC by ravjotbrar

### Summary

Added library dependency for assembly JAR for connector from maven central.

### Description

When users were running the examples, they had to manually add a lib folder along with the JAR file. This step is now removed by adding the library dependency from maven central in the build.sbt file for each example. 

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-77164

### Additional Reviewers

@alexr-bq 
@jonathanl-bq 
@alexey-temnikov

2021-05-14 19:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vertica/spark-connector?pullRequest=80) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vertica/spark-connector?pullRequest=80) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vertica/spark-connector?pullRequest=80) it.</sub>

2021-05-14 20:40 UTC, alexr-bq approved these changes
Looks good! Sign the CLA

2021-05-14 20:40 UTC, alexr-bq commented on examples/demo/build.sbt
> +libraryDependencies += "com.vertica.spark" % "vertica-spark" % "2.0.0-rc0"
May as well make this consistent with the others and use the Seq

2021-05-14 20:53 UTC, alexr-bq commented
Just to confirm: you tested this with nothing in lib/ dir?

2021-05-14 20:54 UTC, ravjotbrar commented on examples/demo/build.sbt
> +libraryDependencies += "com.vertica.spark" % "vertica-spark" % "2.0.0-rc0"
Done

2021-05-14 20:57 UTC, ravjotbrar commented
> Just to confirm: you tested this with nothing in lib/ dir?

That's right. No lib directory in any of the examples.

2021-05-14 22:24 UTC, jonathanl-bq requested changes

2021-05-14 22:24 UTC, jonathanl-bq commented on examples/README.md
> +Now just run `sbt "run [CASE]"` from the `/spark-connector/examples/demo` directory.
We should be more general and state how to run any of the examples, not just the cases from the demo example.

2021-05-14 22:44 UTC, ravjotbrar commented on examples/README.md
> +Now just run `sbt "run [CASE]"` from the `/spark-connector/examples/demo` directory.
What I'm thinking is to use the basic-write example as a case in the demo example. We already have a basicRead case, so the basic-read example seems redundant. This way, all specific examples/cases are organized in one directory. What do you think?

2021-05-14 23:05 UTC, jonathanl-bq commented on examples/README.md
> +Now just run `sbt "run [CASE]"` from the `/spark-connector/examples/demo` directory.
I'm okay with combining some of the other examples into the demo project, though I'm not sure what @alexr-bq thinks. I'm more concerned that there's now only instructions on how to run examples from the demo project. The new README doesn't explain how to run the Kerberos example, or any other future examples we might add (e.g. S3, TLS, etc.).

2021-05-17 15:52 UTC, ravjotbrar commented on examples/README.md
> +Now just run `sbt "run [CASE]"` from the `/spark-connector/examples/demo` directory.
I'll change that in the ticket that involves updating the documentation of the README.

2021-05-17 18:37 UTC, jonathanl-bq commented on examples/README.md
> +Now just run `sbt "run [CASE]"` from the `/spark-connector/examples/demo` directory.
Okay, fair enough.

2021-05-17 18:37 UTC, jonathanl-bq approved these changes

2021-05-18 20:55 UTC, merged