Ver 76342: S3: Add options to connector for access key
vertica/spark-connector pull request #83
Opened 2021-05-18 00:19 UTC by jonathanl-bq

### Summary

This change adds support for connecting to S3. It also exposes a few new AWS connector options.

### Description

Environment variables are read to set the access key ID, secret access key, and region for AWS. Config and error tests are added. I manually tested that all integration tests pass with S3 being used instead of HDFS. Documentation was also updated with instructions on how to use the connector with S3 + new connector options.

### Related Issue

http://jira.verticacorp.com:8080/jira/browse/VER-76342

### Additional Reviewers

@alexr-bq 
@NerdLogic 
@ravjotbrar

2021-05-18 20:09 UTC, alexr-bq requested changes

2021-05-18 20:09 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +    (sys.env.get("AWS_ACCESS_KEY_ID"), sys.env.get("AWS_SECRET_ACCESS_KEY")) match {
I think our config should have priority over env vars

2021-05-18 20:09 UTC, alexr-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +      case (Some(accessKeyId), Some(secretAccessKey)) => Some(AWSAuth(accessKeyId, secretAccessKey)).validNec
Can we also check the spark context for these settings being set that way. Want to cover the bases of the way users might already be setting these for spark.

2021-05-19 17:08 UTC, alexr-bq reviewed
Add note

2021-05-19 17:08 UTC, alexr-bq commented on README.md
> +| aws_access_key_id                              | String                                             | The access key ID for S3. Specifying this option sets the access key ID at the session level. A
Add note to staging_fs_url to use s3a://

2021-05-20 00:12 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +      case (Some(accessKeyId), Some(secretAccessKey)) => Some(AWSAuth(accessKeyId, secretAccessKey)).validNec
Done, but it did mean bringing SparkSession into our config unit tests.

2021-05-20 19:36 UTC, alexr-bq approved these changes

2021-05-20 20:28 UTC, merged