Errors for old connector options
vertica/spark-connector pull request #95
Opened 2021-05-28 20:12 UTC by alexr-bq

### Summary

Errors for old connector options.

### Description

If there are other errors, add helpful messages about old options. If the options are otherwise good, then just warn the user.

### Related Issue

VER-76089

### Additional Reviewers

@jonathanl-bq 
@ravjotbrar

2021-05-28 22:32 UTC, jonathanl-bq requested changes

2021-05-28 22:32 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +    oldList.indices.filter(i => config.contains(oldList(i))).map(i => {
oldList.zip(replacementsList).filter().map() instead so we can avoid any chance of index out of bounds errors.

2021-05-28 22:32 UTC, jonathanl-bq commented on connector/src/main/scala/com/vertica/spark/datasource/core/DSConfigSetup.scala
> +  def logOrAppendErrorsForOldConnectorOptions[T](config: Map[String, String], res: ValidationResult[T], logger: Logger): ValidationResult[T]= {
nit: space before = sign

2021-05-31 18:34 UTC, ravjotbrar approved these changes

2021-05-31 19:07 UTC, merged